spring.application.name=usercard
#validate.server.url=http://host.docker.internal:8081/email/validate
validate.server.url=http://localhost:8081

#properties
usercard.id.start=0
error.email.nullException=Email cannot be empty
error.email.invalid=Email failed validation
error.email.duplicate=Email already exists