spring.application.name=usercard
#validate.server.url=http://host.docker.internal:8081/email/validate
validate.server.url=http://localhost:8081

#properties
usercard.id.start=0
error.email.nullException=Email ?? ????? ???? ??????
error.email.invalid=Email ?? ?????? ?????????
error.email.duplicate=Email ??? ??????????